name: Continuous Build
on: [push]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  lint:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - run: yarn test